#############################################################################
# Makefile for building: RecMasterNCutter
# Generated by qmake (2.01a) (Qt 4.7.4) on: So. Okt 9 21:26:27 2011
# Project:  RecMasterNCutter.pro
# Template: app
# Command: /usr/bin/qmake -spec /usr/share/qt4/mkspecs/linux-g++-32 -o Makefile RecMasterNCutter.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQUAZIP_STATIC -DQT_NO_DEBUG -DQT_MULTIMEDIA_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m32 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m32 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-32 -I. -I/usr/include/QtCore -I/usr/include/QtGui -I/usr/include/QtMultimedia -I/usr/include -Iquazip -I. -I.
LINK          = g++
LFLAGS        = -m32 -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib -lz -lQtMultimedia -L/usr/lib -L/usr/X11R6/lib -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		waveform.cpp \
		wavedata.cpp \
		marks.cpp \
		markimages.cpp \
		icondelegate.cpp \
		savetracks.cpp \
		audiooutput.cpp \
		wavfile.cpp \
		optionsdialog.cpp \
		buttonstateitemdelegate.cpp \
		buttonstate.cpp \
		buttonstatewidget.cpp \
		quazip/zip.c \
		quazip/unzip.c \
		quazip/quazipnewinfo.cpp \
		quazip/quazipfile.cpp \
		quazip/quazip.cpp \
		quazip/quacrc32.cpp \
		quazip/quaadler32.cpp \
		quazip/qioapi.cpp \
		quazip/JlCompress.cpp \
		ziprw.cpp moc_mainwindow.cpp \
		moc_waveform.cpp \
		moc_wavedata.cpp \
		moc_marks.cpp \
		moc_markimages.cpp \
		moc_icondelegate.cpp \
		moc_savetracks.cpp \
		moc_audiooutput.cpp \
		moc_optionsdialog.cpp \
		moc_buttonstateitemdelegate.cpp \
		moc_buttonstatewidget.cpp \
		moc_quazipfile.cpp \
		moc_ziprw.cpp \
		qrc_icons.cpp
OBJECTS       = main.o \
		mainwindow.o \
		waveform.o \
		wavedata.o \
		marks.o \
		markimages.o \
		icondelegate.o \
		savetracks.o \
		audiooutput.o \
		wavfile.o \
		optionsdialog.o \
		buttonstateitemdelegate.o \
		buttonstate.o \
		buttonstatewidget.o \
		zip.o \
		unzip.o \
		quazipnewinfo.o \
		quazipfile.o \
		quazip.o \
		quacrc32.o \
		quaadler32.o \
		qioapi.o \
		JlCompress.o \
		ziprw.o \
		moc_mainwindow.o \
		moc_waveform.o \
		moc_wavedata.o \
		moc_marks.o \
		moc_markimages.o \
		moc_icondelegate.o \
		moc_savetracks.o \
		moc_audiooutput.o \
		moc_optionsdialog.o \
		moc_buttonstateitemdelegate.o \
		moc_buttonstatewidget.o \
		moc_quazipfile.o \
		moc_ziprw.o \
		qrc_icons.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		RecMasterNCutter.pro
QMAKE_TARGET  = RecMasterNCutter
DESTDIR       = 
TARGET        = RecMasterNCutter

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h ui_optionsdialog.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: RecMasterNCutter.pro  /usr/share/qt4/mkspecs/linux-g++-32/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtMultimedia.prl \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++-32 -o Makefile RecMasterNCutter.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtMultimedia.prl:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++-32 -o Makefile RecMasterNCutter.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/RecMasterNCutter1.0.0 || $(MKDIR) .tmp/RecMasterNCutter1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/RecMasterNCutter1.0.0/ && $(COPY_FILE) --parents mainwindow.h waveform.h wavedata.h marks.h markimages.h icondelegate.h savetracks.h audiooutput.h wavfile.h optionsdialog.h buttonstateitemdelegate.h buttonstate.h buttonstatewidget.h quazip/zip.h quazip/unzip.h quazip/quazipnewinfo.h quazip/quazipfileinfo.h quazip/quazipfile.h quazip/quazip_global.h quazip/quazip.h quazip/quacrc32.h quazip/quachecksum32.h quazip/quaadler32.h quazip/JlCompress.h quazip/ioapi.h quazip/crypt.h quazip/zconf.h quazip/zlib.h ziprw.h .tmp/RecMasterNCutter1.0.0/ && $(COPY_FILE) --parents icons.qrc .tmp/RecMasterNCutter1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp waveform.cpp wavedata.cpp marks.cpp markimages.cpp icondelegate.cpp savetracks.cpp audiooutput.cpp wavfile.cpp optionsdialog.cpp buttonstateitemdelegate.cpp buttonstate.cpp buttonstatewidget.cpp quazip/zip.c quazip/unzip.c quazip/quazipnewinfo.cpp quazip/quazipfile.cpp quazip/quazip.cpp quazip/quacrc32.cpp quazip/quaadler32.cpp quazip/qioapi.cpp quazip/JlCompress.cpp ziprw.cpp .tmp/RecMasterNCutter1.0.0/ && $(COPY_FILE) --parents mainwindow.ui optionsdialog.ui .tmp/RecMasterNCutter1.0.0/ && $(COPY_FILE) --parents RecMasterNCutter_de.ts .tmp/RecMasterNCutter1.0.0/ && (cd `dirname .tmp/RecMasterNCutter1.0.0` && $(TAR) RecMasterNCutter1.0.0.tar RecMasterNCutter1.0.0 && $(COMPRESS) RecMasterNCutter1.0.0.tar) && $(MOVE) `dirname .tmp/RecMasterNCutter1.0.0`/RecMasterNCutter1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/RecMasterNCutter1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_waveform.cpp moc_wavedata.cpp moc_marks.cpp moc_markimages.cpp moc_icondelegate.cpp moc_savetracks.cpp moc_audiooutput.cpp moc_optionsdialog.cpp moc_buttonstateitemdelegate.cpp moc_buttonstatewidget.cpp moc_quazipfile.cpp moc_ziprw.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_waveform.cpp moc_wavedata.cpp moc_marks.cpp moc_markimages.cpp moc_icondelegate.cpp moc_savetracks.cpp moc_audiooutput.cpp moc_optionsdialog.cpp moc_buttonstateitemdelegate.cpp moc_buttonstatewidget.cpp moc_quazipfile.cpp moc_ziprw.cpp
moc_mainwindow.cpp: marks.h \
		markimages.h \
		savetracks.h \
		audiooutput.h \
		optionsdialog.h \
		mainwindow.h
	/usr/bin/moc $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_waveform.cpp: wavedata.h \
		marks.h \
		waveform.h
	/usr/bin/moc $(DEFINES) $(INCPATH) waveform.h -o moc_waveform.cpp

moc_wavedata.cpp: wavedata.h
	/usr/bin/moc $(DEFINES) $(INCPATH) wavedata.h -o moc_wavedata.cpp

moc_marks.cpp: marks.h
	/usr/bin/moc $(DEFINES) $(INCPATH) marks.h -o moc_marks.cpp

moc_markimages.cpp: marks.h \
		markimages.h
	/usr/bin/moc $(DEFINES) $(INCPATH) markimages.h -o moc_markimages.cpp

moc_icondelegate.cpp: markimages.h \
		marks.h \
		icondelegate.h
	/usr/bin/moc $(DEFINES) $(INCPATH) icondelegate.h -o moc_icondelegate.cpp

moc_savetracks.cpp: marks.h \
		savetracks.h
	/usr/bin/moc $(DEFINES) $(INCPATH) savetracks.h -o moc_savetracks.cpp

moc_audiooutput.cpp: marks.h \
		audiooutput.h
	/usr/bin/moc $(DEFINES) $(INCPATH) audiooutput.h -o moc_audiooutput.cpp

moc_optionsdialog.cpp: optionsdialog.h
	/usr/bin/moc $(DEFINES) $(INCPATH) optionsdialog.h -o moc_optionsdialog.cpp

moc_buttonstateitemdelegate.cpp: buttonstateitemdelegate.h
	/usr/bin/moc $(DEFINES) $(INCPATH) buttonstateitemdelegate.h -o moc_buttonstateitemdelegate.cpp

moc_buttonstatewidget.cpp: buttonstate.h \
		buttonstatewidget.h
	/usr/bin/moc $(DEFINES) $(INCPATH) buttonstatewidget.h -o moc_buttonstatewidget.cpp

moc_quazipfile.cpp: quazip/quazip_global.h \
		quazip/quazip.h \
		quazip/zip.h \
		quazip/zlib.h \
		quazip/zconf.h \
		quazip/ioapi.h \
		quazip/unzip.h \
		quazip/quazipfileinfo.h \
		quazip/quazipnewinfo.h \
		quazip/quazipfile.h
	/usr/bin/moc $(DEFINES) $(INCPATH) quazip/quazipfile.h -o moc_quazipfile.cpp

moc_ziprw.cpp: ziprw.h
	/usr/bin/moc $(DEFINES) $(INCPATH) ziprw.h -o moc_ziprw.cpp

compiler_rcc_make_all: qrc_icons.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_icons.cpp
qrc_icons.cpp: icons.qrc \
		RecMasterNCutter_de.qm \
		buttonstyleicons/WaveDiscTick24.png \
		buttonstyleicons/WaveDiscGear24.png \
		buttonstyleicons/fileopen_proc.png \
		buttonstyleicons/notecompressTick24.png \
		buttonstyleicons/WaveDiscGearShaddow24.png \
		buttonstyleicons/notecompressGear24.png \
		buttonstyleicons/fileopen.png \
		buttonstyleicons/notecompressGearShaddow24.png \
		buttonstyleicons/notecompress24.png \
		buttonstyleicons/WaveDiskette.png \
		icons/End_Track.png \
		icons/End_Silence.png \
		icons/media_playlist_refresh.png \
		icons/go-end-24.png \
		icons/Add_1.png \
		icons/go-next-24.png \
		icons/Add_2.png \
		icons/waveform.png \
		icons/Add_3.png \
		icons/go-first-24.png \
		icons/Add_4.png \
		icons/Add_Actual.png \
		icons/icon.png \
		icons/Start_Silence.png \
		icons/fadeOut.png \
		icons/go-previous-24.png \
		icons/zoom-in.svg \
		icons/saveWave.png \
		icons/standardbutton-closetab-16.png \
		icons/delete.png \
		icons/player_play_atline.png \
		icons/open.png \
		icons/Start_Track.png \
		icons/zoom-out.svg \
		icons/fadeIn.png \
		icons/player_play.png \
		icons/save.png \
		icons/rec.png \
		icons/go-pos1-24.png \
		icons/openrec.png \
		icons/go-last-24.png \
		icons/Standard.png \
		icons/player_stop.png
	/usr/bin/rcc -name icons icons.qrc -o qrc_icons.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_optionsdialog.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_optionsdialog.h
ui_mainwindow.h: mainwindow.ui \
		waveform.h \
		wavedata.h \
		marks.h
	/usr/bin/uic mainwindow.ui -o ui_mainwindow.h

ui_optionsdialog.h: optionsdialog.ui
	/usr/bin/uic optionsdialog.ui -o ui_optionsdialog.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		marks.h \
		markimages.h \
		savetracks.h \
		audiooutput.h \
		optionsdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp icondelegate.h \
		markimages.h \
		marks.h \
		mainwindow.h \
		savetracks.h \
		audiooutput.h \
		optionsdialog.h \
		ui_mainwindow.h \
		buttonstateitemdelegate.h \
		buttonstate.h \
		wavfile.h \
		ziprw.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

waveform.o: waveform.cpp waveform.h \
		wavedata.h \
		marks.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o waveform.o waveform.cpp

wavedata.o: wavedata.cpp wavedata.h \
		wavfile.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o wavedata.o wavedata.cpp

marks.o: marks.cpp marks.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o marks.o marks.cpp

markimages.o: markimages.cpp markimages.h \
		marks.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o markimages.o markimages.cpp

icondelegate.o: icondelegate.cpp icondelegate.h \
		markimages.h \
		marks.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o icondelegate.o icondelegate.cpp

savetracks.o: savetracks.cpp savetracks.h \
		marks.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o savetracks.o savetracks.cpp

audiooutput.o: audiooutput.cpp audiooutput.h \
		marks.h \
		wavfile.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o audiooutput.o audiooutput.cpp

wavfile.o: wavfile.cpp wavfile.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o wavfile.o wavfile.cpp

optionsdialog.o: optionsdialog.cpp optionsdialog.h \
		ui_optionsdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o optionsdialog.o optionsdialog.cpp

buttonstateitemdelegate.o: buttonstateitemdelegate.cpp buttonstateitemdelegate.h \
		buttonstate.h \
		buttonstatewidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o buttonstateitemdelegate.o buttonstateitemdelegate.cpp

buttonstate.o: buttonstate.cpp buttonstate.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o buttonstate.o buttonstate.cpp

buttonstatewidget.o: buttonstatewidget.cpp buttonstatewidget.h \
		buttonstate.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o buttonstatewidget.o buttonstatewidget.cpp

zip.o: quazip/zip.c quazip/zlib.h \
		quazip/zconf.h \
		quazip/zip.h \
		quazip/ioapi.h \
		quazip/quazip_global.h \
		quazip/crypt.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o zip.o quazip/zip.c

unzip.o: quazip/unzip.c quazip/zlib.h \
		quazip/zconf.h \
		quazip/unzip.h \
		quazip/ioapi.h \
		quazip/crypt.h \
		quazip/quazip_global.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o unzip.o quazip/unzip.c

quazipnewinfo.o: quazip/quazipnewinfo.cpp quazip/quazipnewinfo.h \
		quazip/quazip_global.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o quazipnewinfo.o quazip/quazipnewinfo.cpp

quazipfile.o: quazip/quazipfile.cpp quazip/quazipfile.h \
		quazip/quazip_global.h \
		quazip/quazip.h \
		quazip/zip.h \
		quazip/zlib.h \
		quazip/zconf.h \
		quazip/ioapi.h \
		quazip/unzip.h \
		quazip/quazipfileinfo.h \
		quazip/quazipnewinfo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o quazipfile.o quazip/quazipfile.cpp

quazip.o: quazip/quazip.cpp quazip/quazip.h \
		quazip/zip.h \
		quazip/zlib.h \
		quazip/zconf.h \
		quazip/ioapi.h \
		quazip/unzip.h \
		quazip/quazip_global.h \
		quazip/quazipfileinfo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o quazip.o quazip/quazip.cpp

quacrc32.o: quazip/quacrc32.cpp quazip/quacrc32.h \
		quazip/quachecksum32.h \
		quazip/quazip_global.h \
		quazip/zlib.h \
		quazip/zconf.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o quacrc32.o quazip/quacrc32.cpp

quaadler32.o: quazip/quaadler32.cpp quazip/quaadler32.h \
		quazip/quachecksum32.h \
		quazip/quazip_global.h \
		quazip/zlib.h \
		quazip/zconf.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o quaadler32.o quazip/quaadler32.cpp

qioapi.o: quazip/qioapi.cpp quazip/zlib.h \
		quazip/zconf.h \
		quazip/ioapi.h \
		quazip/quazip_global.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qioapi.o quazip/qioapi.cpp

JlCompress.o: quazip/JlCompress.cpp quazip/JlCompress.h \
		quazip/quazip.h \
		quazip/zip.h \
		quazip/zlib.h \
		quazip/zconf.h \
		quazip/ioapi.h \
		quazip/unzip.h \
		quazip/quazip_global.h \
		quazip/quazipfileinfo.h \
		quazip/quazipfile.h \
		quazip/quazipnewinfo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o JlCompress.o quazip/JlCompress.cpp

ziprw.o: ziprw.cpp ziprw.h \
		quazip/quazip.h \
		quazip/zip.h \
		quazip/zlib.h \
		quazip/zconf.h \
		quazip/ioapi.h \
		quazip/unzip.h \
		quazip/quazip_global.h \
		quazip/quazipfileinfo.h \
		quazip/quazipfile.h \
		quazip/quazipnewinfo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ziprw.o ziprw.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_waveform.o: moc_waveform.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_waveform.o moc_waveform.cpp

moc_wavedata.o: moc_wavedata.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_wavedata.o moc_wavedata.cpp

moc_marks.o: moc_marks.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_marks.o moc_marks.cpp

moc_markimages.o: moc_markimages.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_markimages.o moc_markimages.cpp

moc_icondelegate.o: moc_icondelegate.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_icondelegate.o moc_icondelegate.cpp

moc_savetracks.o: moc_savetracks.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_savetracks.o moc_savetracks.cpp

moc_audiooutput.o: moc_audiooutput.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_audiooutput.o moc_audiooutput.cpp

moc_optionsdialog.o: moc_optionsdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_optionsdialog.o moc_optionsdialog.cpp

moc_buttonstateitemdelegate.o: moc_buttonstateitemdelegate.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_buttonstateitemdelegate.o moc_buttonstateitemdelegate.cpp

moc_buttonstatewidget.o: moc_buttonstatewidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_buttonstatewidget.o moc_buttonstatewidget.cpp

moc_quazipfile.o: moc_quazipfile.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_quazipfile.o moc_quazipfile.cpp

moc_ziprw.o: moc_ziprw.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ziprw.o moc_ziprw.cpp

qrc_icons.o: qrc_icons.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_icons.o qrc_icons.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

